In [1]:
import pandas as pd

In [2]:
pd.read_csv("/media/bendico765/Crucial X9/MRI Lesions/t2_original_masks.csv", index_col=0)

,Patient id,tumor/benign,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,...,original_glszm_SmallAreaHighGrayLevelEmphasis,original_glszm_SmallAreaLowGrayLevelEmphasis,original_glszm_ZoneEntropy,original_glszm_ZonePercentage,original_glszm_ZoneVariance,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,AMBL-001,1.0,0.528082,0.375975,8.551139,22.743875,16.077739,26.863471,28.393673,28.514781,...,24.788206,0.034939,5.314315,0.108681,1958.399747,2.180991,0.005592,62.527685,0.025755,0.446372
1,AMBL-001,1.0,0.336182,0.293785,7.651833,26.045677,12.776208,29.951350,30.613497,30.873714,...,41.082885,0.023399,5.547501,0.238139,195.776398,1.788708,0.006925,154.330567,0.092908,0.717002
2,AMBL-003,1.0,0.563923,0.394181,8.781372,22.277510,15.791279,22.006371,25.548437,28.399439,...,70.737083,0.007865,5.719785,0.286100,35.099034,0.405674,0.011708,198.482591,0.141787,1.564591
3,AMBL-004,0.0,0.841780,0.544635,5.781581,10.615516,12.384042,12.202597,11.972233,13.409930,...,31.148410,0.035389,5.454511,0.186047,98.095486,0.465258,0.021809,160.600622,0.126481,2.210714
4,AMBL-005,1.0,0.761755,0.641036,20.245467,31.582394,31.583382,37.458189,36.670108,41.917128,...,111.580934,0.008027,6.738264,0.163246,1264.319024,2.658235,0.001295,537.133281,0.089851,0.434948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,AMBL-629,0.0,0.536967,0.460586,5.507756,11.958154,7.911026,13.636432,13.534500,13.651654,...,31.744319,0.048109,5.118563,0.155763,204.283600,0.435903,0.025460,81.021906,0.032208,2.603894
160,AMBL-629,0.0,0.812137,0.391481,3.922691,10.020136,9.023000,10.504158,11.831447,11.831447,...,43.623571,0.023636,5.339177,0.271127,41.123630,0.374538,0.025025,173.136502,0.115295,2.871139
161,AMBL-629,0.0,0.610620,0.593518,5.917674,9.970505,8.345406,12.882246,12.313155,13.651654,...,52.539725,0.031165,5.353770,0.372694,13.661994,0.338195,0.027282,282.541708,0.168557,3.606316
162,AMBL-631,1.0,0.484699,0.354789,22.866333,64.450573,64.887851,44.239366,47.337801,71.219078,...,92.191750,0.005751,6.400818,0.173808,2789.922389,4.276705,0.000770,488.337249,0.056097,0.302017
163,AMBL-631,1.0,0.827030,0.748447,9.120478,12.185868,14.114938,14.782891,14.212361,15.328236,...,45.470079,0.020261,5.466695,0.188206,304.535156,1.498264,0.009054,102.712223,0.100210,0.634221

In [3]:
pd.read_csv("/media/bendico765/Crucial X9/MRI Lesions/lesions_df.csv", index_col=0)

,Patient ID,tumor/benign,Registered Ax T2 FSE path,Slice Location,Breast,z_indexes,y_indexes,x_indexes,z_offset,y_offset,x_offset,Roi mask Filepath,Cleaned Roi mask Filepath,Pixel Spacing,Slice Thickness,RobustScaled Registered Ax T2 FSE path,Registered AX Sen Vibrant MultiPhase path
0,AMBL-001,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-60.85,L,"[82, 83, 84, 85, 86, 87]","[172, 173, 174, 175, 176, 177, 178, 179, 180, ...","[142, 143, 144, 145, 146, 147, 148, 149, 150, ...",6,42,23,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
1,AMBL-001,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-56.85,R,"[82, 83, 84, 85]","[188, 189, 190, 191, 192, 193, 194, 195, 196, ...","[360, 361, 362, 363, 364, 365, 366, 367, 368, ...",4,46,17,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
12,AMBL-003,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-2.76,R,"[49, 50, 51, 52, 53, 54, 55]","[178, 179, 180, 181, 182, 183, 184, 185, 186, ...","[357, 358, 359, 360, 361, 362, 363, 364, 365, ...",7,40,21,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
18,AMBL-004,0.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-51.98,L,"[81, 82, 83, 84, 85]","[163, 164, 165, 166, 167, 168, 169, 170, 171, ...","[147, 148, 149, 150, 151, 152, 153, 154, 155, ...",5,18,13,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
24,AMBL-005,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-28.46,R,"[54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 6...","[194, 195, 196, 197, 198, 199, 200, 201, 202, ...","[379, 380, 381, 382, 383, 384, 385, 386, 387, ...",13,55,47,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179,AMBL-629,0.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,1.93,R,"[55, 56, 57]","[159, 160, 161, 162, 163, 164, 165, 166, 167, ...","[391, 392, 393, 394, 395, 396, 397, 398, 399, ...",3,21,10,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6445,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
1180,AMBL-629,0.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-48.07,R,"[81, 82]","[147, 148, 149, 150, 151, 152, 153, 154, 155, ...","[373, 374, 375, 376, 377, 378, 379, 380, 381, ...",2,17,14,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6445,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
1181,AMBL-629,0.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,-32.07,R,"[73, 74, 75]","[156, 157, 158, 159, 160, 161, 162, 163, 164, ...","[338, 339, 340, 341, 342, 343, 344, 345, 346, ...",3,20,12,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6445,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
1188,AMBL-631,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,33.93,L,"[37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 4...","[143, 144, 145, 146, 147, 148, 149, 150, 151, ...","[99, 100, 101, 102, 103, 104, 105, 106, 107, 1...",22,85,87,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...
1189,AMBL-631,1.0,/media/bendico765/Crucial X9/MRI Lesions/manif...,25.93,L,"[43, 44, 45, 46, 47, 48]","[154, 155, 156, 157, 158, 159, 160, 161, 162, ...","[131, 132, 133, 134, 135, 136, 137, 138, 139, ...",6,20,20,/media/bendico765/Crucial X9/MRI Lesions/Roi m...,/media/bendico765/Crucial X9/MRI Lesions/Clean...,0.6641,2.0,/media/bendico765/Crucial X9/MRI Lesions/Robus...,/media/bendico765/Crucial X9/MRI Lesions/manif...